cc_binary(
  name = "throttling_proxy_example",
  srcs = ["throttling_proxy_example.cc"],
  deps = [
  	"//common/dstage:dstage_base",
    "//common/dstage:throttler",
    "//common/dstage:dans_throttling_proxy",
    "@glog//:main",
    "@gflags//:main",
  ],
)