cc_library(
    name = "glog",
    srcs = ["libglog.so"],
    hdrs = [":glog/log_severity.h",
	    ":glog/logging.h",
	    ":glog/raw_logging.h",
	    ":glog/stl_logging.h",
	    ":glog/vlog_is_on.h"],
    visibility = ["//visibility:public"],
)
