cc_library(
    name = "gflags",
    srcs = ["libgflags.so"],
    hdrs = [":gflags/gflags.h",
	    ":gflags/gflags_completions.h",
	    ":gflags/gflags_declare.h",
	    ":gflags/gflags_gflags.h"],
    visibility = ["//visibility:public"],
)
